service: cognito-auth-api
frameworkVersion: '3'

plugins:
  - serverless-esbuild

package:
  individually: true

provider:
  name: aws
  region: sa-east-1
  runtime: nodejs20.x
  deploymentMethod: direct
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminGetUser
          Resource: !GetAtt LiveUserPool.Arn
  environment:
    COGNITO_CLIENT_ID: !Ref LiveUserPoolClient
    COGNITO_POOL_ID: !Ref LiveUserPool
  httpApi:
    authorizers:
      CognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !GetAtt LiveUserPool.ProviderURL
        audience:
          - !Ref LiveUserPoolClient

custom:
  esbuild:
  bundle: true
  minify: true
  sourcemap: false
  target: node20
  exclude:
    - '@aws-sdk/*'
  define:
    require.resolve: undefined
  platform: node
  concurrency: 10

resources:
  Resources:
    LiveUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: LiveUserPool
        MfaConfiguration: OFF
        AutoVerifiedAttributes:
          - email
        AdminCreateUserConfig:
          AllowAdminCreateUserOnly: false
        UsernameAttributes:
          - email
        AccountRecoverySettings:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        Policies:
          PasswordPolicy:
            MinimumLenght: 10
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
            TemporaryPasswordValidityDays: 3
        Schema:
          - Name: given_name
            Mutable: true
            Required: true
            AttributeDataType: String
          - Name: family_name
            Mutable: true
            Required: true
            AttributeDataType: String
        DeletionProtection: INACTIVE
    LiveUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: LiveUserPoolClient
        UserPoolId: !Ref LiveUserPool
        ExplicitAuthFlows:
          - ALLOW_USER_PASSWORD_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
        AccessTokenValidity: 3
        RefreshTokenValidity: 30
        TokenValidityUnits:
          AccessToken: hours
          RefreshToken: days

functions:
  cognitoCustomMessage:
    handler: src/functions/cognitoCustomMessage.handler
    events:
      - cognitoUserPool:
          pool: LiveUserPool
          trigger: CustomMessage
          # existing: true
          # forceDeploy: true
  signUp:
    handler: src/functions/signUp.handler
    events:
      - httpApi:
          method: POST
          path: /auth/sing-up
  signIn:
    handler: src/functions/signIn.handler
    events:
      - httpApi:
          method: POST
          path: /auth/sing-in
  accountConfirmation:
    handler: src/functions/accountConfirmation.handler
    events:
      - httpApi:
          method: POST
          path: /auth/account-confirmation
  refreshToken:
    handler: src/functions/refreshToken.handler
    events:
      - httpApi:
          method: POST
          path: /auth/refresh-token
  forgotPassword:
    handler: src/functions/forgotPassword.handler
    events:
      - httpApi:
          method: POST
          path: /auth/forgot-password
  resetPassword:
    handler: src/functions/resetPassword.handler
    events:
      - httpApi:
          method: POST
          path: /auth/reset-password
  profile:
    handler: src/functions/profile.handler
    events:
      - httpApi:
          method: GET
          path: /auth/profile
          authorizer:
            name: CognitoAuthorizer
